---
title: "210 Project"
author: "Austin Brown and Ryan Yu"
format: pdf
---
```{r}
library(tidymodels)
library(tidyverse)
library(Stat2Data)
library(MASS)
library(caret)
library(leaps)
library(glmnet)
library(broom)
library(nnet)
library(ggfortify)
library(naniar)
library(UpSetR)
library(lme4)
library(ggplot2)
```

```{r}
player_data <- read.csv(
  "https://query.data.world/s/5zns27g5v3ce74zgwtcosxygtexpef?dws=00000", 
  header=TRUE, stringsAsFactors=FALSE)
player_data <-subset(player_data, select = -c(url,birth_date, X) )
player_data$career_length <- player_data$active_to - player_data$active_from
```


Potential Cleaning for College Column
```{r}
#player_data$college <- gsub("\\bUniversity \\b", "", player_data$college)
# Load library
#library(stringr)

# If there are two schools listed, only keep the first one
#player_data$college <- str_extract(player_data$college, "^[^,]*")
#player_data$college <- gsub("\\s*University\\s*", "", player_data$college)
#player_data$college <- gsub("(?i)\\s*of\\s*", "", player_data$college)
#unique(player_data$college)
```

Position Variable
```{r}
#test
player_data$position<- substring(player_data$position, first=1, last=1)

```

EDA
```{r Graph1}
# filter for min attempts, also change axis lengths
player_data %>% filter(NBA__3ptapg > 0.5) %>% filter(NCAA__3ptapg > 0.5) %>%
  filter(NBA_g_played > 20) %>% filter(NCAA_games > 20) %>%
ggplot(mapping = aes(x = NCAA__3ptpct, y = NBA__3ptpct)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  labs(title = "College vs. NBA 3pt. Percentage", 
       x = "NCAA 3pt. %", y = "NBA 3pt. %") + ylim(0, .5) + xlim(0, .5)
```
```{r Graph2}
player_data %>% filter(NBA__3ptapg > 0.5) %>% filter(NCAA_ftapg > 0.3) %>%
  filter(NBA_g_played > 20) %>% filter(NCAA_games > 20) %>%
ggplot(mapping = aes(x = NCAA_ft, y = NBA__3ptpct)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  labs(title = "College FT Percentage vs. NBA 3pt. Percentage", 
       x = "NCAA FT %", y = "NBA 3pt. %") + ylim(0, 0.5) + xlim(.3, 1)
```
```{r Graph3}
player_data %>% filter(position == c("G", "F", "C")) %>% 
  ggplot(mapping = aes(y = career_length, x = position)) +
  geom_boxplot() +  labs(title = "Career Length Distributions by Position", 
       x = "Position", y = "Career Length (years)")
```


Ryan Model
```{r}
options(digits = 3)

# Subset the columns used in the linear regression model
model_data <- player_data[c("NBA__3ptpct", "NCAA_ft", "NCAA__3ptpct", 
                           "NCAA_fgpct")]

# Remove observations with missing values from the subset
model_data <- na.omit(model_data)

nba3pt <- lm(NBA__3ptpct ~ NCAA_ft + NCAA__3ptpct + 
               NCAA_fgpct, data = model_data)
tidy(nba3pt)
```

## Assumptions
```{r Residual Plot}
nba3pt_aug <- augment(nba3pt)
ggplot(nba3pt_aug, aes(x = .fitted, y = .resid)) +
geom_point() +
geom_hline(yintercept = 0, color = "darkred") +
labs(x = "Fitted (predicted) value", y = "Residual") +
theme_bw()
```
```{r Theoretical Quantiles Plot}
ggplot(nba3pt_aug, aes(sample = .resid)) +
stat_qq() +
stat_qq_line() +
theme_bw() +
labs(x = "Theoretical quantiles",
y = "Sample quantiles")
```



Austin Model
```{r}
```
